### ISSUE TITLE
render window doesn't change appearance

### ISSUE THREAD

**Issue by kncrane** [NotAnyMike/gym#35]
Hi, just a quick one .. when pass in `grayscale=1` and `show_info_panel=0` as parameters, can see that parameters have been received since printing observation to terminal gives list of four-value arrays (four stacked single-channel frames) as opposed to three-value arrays (one three-channel frame), but the render window continues to show track in colour and with info panel - is it meant to?

Thank you

**Comment by NotAnyMike** [comment]
Hello there. Yes, the GUI is only meant for humans so we keep showing the colours and info panel. But the observations returned by step will be black and white and without the info panel if you configured it like that.
