### ISSUE TITLE
How to change the map ?

### ISSUE THREAD

**Issue by ajithvcoder** [NotAnyMike/gym#36]
I want to use different map .Is it possible to change by changing a single picture also which is same as the size of original map . if so where should i change that picture

**Comment by NotAnyMike** [comment]
The map is not a picture, it is generated randomly and has low-level information that helps the environment. Here ([link](https://github.com/NotAnyMike/gym/blob/794bcdf7f1e2a13c47451b6132b6e7ac626cf8d8/gym/envs/box2d/car_racing.py#L275)) you can see all the options to configure the environment and the maps. You can also load maps but generating could be a more complicated task. If you need to have high performance, loading maps could make things faster than generating them.

**Comment by ajithvcoder** [comment]
okay thanks

**Comment by Xand04** [comment]
Hi @NotAnyMike ! Thanks a lot for this excellent repo! I would have a similar question about loading maps. 

I only discovered gym a few days ago and I'm a bit lost with all the features. What would be the best approach for you if I had to recreate a specific circuit from scratch?

Thanks again!
